### ISSUE TITLE
Merge conflict warning

### ISSUE THREAD

**Issue by datawookie** [dominodatalab/low-code-assistant#15]
Hi!

I'm testing up the app deployment functionality. I followed the steps [here](https://dominodatalab.github.io/low-code-jupyter-docs/getting-started/app/deploy/). Everything went as expected up until the point when I pressed the **Sync All Changes** button.

![image](https://user-images.githubusercontent.com/6134409/196749375-d760e8dc-505c-4132-bda8-1ed811e40f25.png)

It's unclear to me what has gone wrong here or what is the correct next step to take. I certainly think that for a new user this would not be a good experience.

In the interests of being able to reproduce the problem I'm not going to choose either of the options presented in the dialog and just leave this as it stands.

Thanks, Andrew.

**Comment by datawookie** [comment]
Additional information:

- The session I was running was plain Jupyter (not JupyterLab). Not sure if this is relevant? Hardware tier was Small (with egress).
- I restarted the workspace and repeated the process and this time it worked fine. However, I still think that this would be a poor first time user experience.

**Comment by mariobuikhuizen** [comment]
This is functionality of Domino, not of LCA.

Perhaps you have a second tab open with the same project, and pushed changes from there earlier?

**Comment by datawookie** [comment]
Aha! Got it. Has not recurred, so this was evidently this "new user" problems! Thanks @mariobuikhuizen!
