### ISSUE TITLE
Test Viz & App deployment on Edge

### ISSUE THREAD

**Issue by jp-domino** [dominodatalab/low-code-assistant#24]
Witnessed a demo today where some major elements did not show up on Edge. 
The user was on an old version of LCA (0.1.0) - so this may have been entirely the problem, but we can please test to make sure @datawookie and update the docs if we are not recommending Edge at this time?

**Comment by datawookie** [comment]
Installing older version of LCA:

```
!python -m pip install --user https://github.com/dominodatalab/low-code-assistant/archive/refs/tags/v0.1.0.tar.gz
```

**Comment by jp-domino** [comment]
That's correct, but please only test on Edge using the latest LCA version

**Comment by datawookie** [comment]
Sure thing. Sorry, that was just a note for my future reference. I've got the old version installed. You mentioned the older version in the initial comment, but I see that this was a misunderstanding on my part. If Edge works with current LCA then it's not a problem. :+1:

**Comment by datawookie** [comment]
@jp-domino I have tested the latest version of LCA () on Edge (106.0.1370.52).

- [X] load data from S3
- [X] load data from BigQuery
- [X] generate simple visualisation (histogram) and
- [X] create and preview simple app.

Screenshots for each of the these below.

![image](https://user-images.githubusercontent.com/6134409/198328870-3a52d569-44bf-49e6-929e-7055ec2492db.png)

![image](https://user-images.githubusercontent.com/6134409/198328896-fb9d0586-67c7-4d55-bc90-5e5eb869b58a.png)

![image](https://user-images.githubusercontent.com/6134409/198328924-c62a26ee-52e8-4ec3-8045-776d6350b968.png)

![image](https://user-images.githubusercontent.com/6134409/198328955-bc299d89-ef45-4e05-8f1e-beeb715eb8b3.png)
