### ISSUE TITLE
Consistent capitalisation

### ISSUE THREAD

**Issue by datawookie** [dominodatalab/low-code-assistant#27]
The menu has inconsistent capitalisation.

![image](https://user-images.githubusercontent.com/6134409/198976899-7d4a02c8-a6e9-4d84-8e0e-257af1b22ac8.png)

Suggest either:

- changing "Data" to "data" or
- changing "text" to "Text" and "snippet" to "Snippet".

**Comment by mariobuikhuizen** [comment]
I agree! Thanks for reporting @datawookie 👍
